package com.kyle.train.mbg.model;

public class UmsAdminRoleRelation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_admin_role_relation.id
     *
     * @mbg.generated Thu Oct 21 13:33:02 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_admin_role_relation.admin_id
     *
     * @mbg.generated Thu Oct 21 13:33:02 CST 2021
     */
    private Long adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_admin_role_relation.role_id
     *
     * @mbg.generated Thu Oct 21 13:33:02 CST 2021
     */
    private Long roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_admin_role_relation.id
     *
     * @return the value of ums_admin_role_relation.id
     *
     * @mbg.generated Thu Oct 21 13:33:02 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_admin_role_relation.id
     *
     * @param id the value for ums_admin_role_relation.id
     *
     * @mbg.generated Thu Oct 21 13:33:02 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_admin_role_relation.admin_id
     *
     * @return the value of ums_admin_role_relation.admin_id
     *
     * @mbg.generated Thu Oct 21 13:33:02 CST 2021
     */
    public Long getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_admin_role_relation.admin_id
     *
     * @param adminId the value for ums_admin_role_relation.admin_id
     *
     * @mbg.generated Thu Oct 21 13:33:02 CST 2021
     */
    public void setAdminId(Long adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_admin_role_relation.role_id
     *
     * @return the value of ums_admin_role_relation.role_id
     *
     * @mbg.generated Thu Oct 21 13:33:02 CST 2021
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_admin_role_relation.role_id
     *
     * @param roleId the value for ums_admin_role_relation.role_id
     *
     * @mbg.generated Thu Oct 21 13:33:02 CST 2021
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
}